services:
  wg-panel:    
    image: ghcr.io/h0sin/wg-panel:latest
    
  wireguarddb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4
    
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    
  wireguard.api:
    image: wireguard.api
    build:
      context: Src
      dockerfile: Services/Api/Wireguard.Api/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
