services:
  wireguarddb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  wireguard.api:
    image: wireguard.api
    build:
      context: Src
      dockerfile: Services/Api/Wireguard.Api/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management
  
  wg-dashboard:
    build:
      context: Src
      dockerfile: wg-dashboard/Dockerfile
  
volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data: