services:
#  rabbitmq:
#    container_name: rabbitmq
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    network_mode: host
#    environment:
#      RABBITMQ_DEFAULT_USER: hossein
#      RABBITMQ_DEFAULT_PASS: hossein*(!^
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#      
  wireguarddb:
    container_name: wireguarddb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=WireguardDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /root/backup/postgres/data:/var/lib/postgresql/data/
    network_mode: host
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "50500:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    depends_on:
      - wireguarddb
  
  wireguard.api:
    user: root
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - "DatabaseSettings:ConnectionString=Host=188.245.125.107;Port=5432;Database=WireguardDb;User Id=admin;Password=admin1234;"
    ports:
      - "8000:8000"
    depends_on:
      - wireguarddb
    volumes:
      - /root/backup/wireguard/interfaces:/etc/wireguard/
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW


