services:
  wireguarddb:
    container_name: wireguarddb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=WireguardDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /root/backup/postgres/data:/var/lib/postgresql/data/
    network_mode: host
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - wireguarddb
  
  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: wireguard
      RABBITMQ_DEFAULT_PASS: hossein
    restart: always
    network_mode: host
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  wireguard.api:
    user: root
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - DatabaseSettings__ConnectionString=Host=localhost;Port=5432;Database=WireguardDb;User Id=admin;Password=admin1234;
      - EventBusSettings__HostAddress=amqp://wireguard:hossein@localhost:5672
    ports:
      - "8000:8000"
    depends_on:
      - wireguarddb
      - rabbitmq
    volumes:
      - /root/backup/wireguard/interfaces:/etc/wireguard/
      - /root/Wireguard/Src/Services/Api/Wireguard.Api/Imperat/rc.local:/etc/rc.local
    network_mode: host
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
